#!/usr/bin/env node
import { readFile, writeFile } from 'node:fs/promises';
import { resolve, dirname, relative } from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const repoRoot = resolve(__dirname, '..', '..', '..');
const bundlePath = resolve(__dirname, '..', 'dist', 'cli-install-embedded.js');
const installPath = resolve(repoRoot, 'bin', 'install');

const MARKER = 'REPO_TOOLKIT_INSTALL_BUNDLE_v1';

async function main() {
  const bundle = (await readFile(bundlePath, 'utf8')).replace(/^#![^\n]*\n/u, '');
  if (new RegExp(`(^|\\n)${MARKER}(\\n|$)`, 'u').test(bundle)) {
    throw new Error(`Refusing to embed bundle: body contains the heredoc marker '${MARKER}'.`);
  }

  const body = bundle.split('\n').filter((line, idx, arr) => {
    if (idx < arr.length && line.trim() === '' && (idx === 0 || idx === arr.length - 1)) {
      return false;
    }
    return true;
  }).join('\n').trim();

  if (!body) {
    throw new Error('Refusing to embed an empty installer bundle.');
  }

  const installPathRel = relative(repoRoot, installPath);
  const bundlePathRel = relative(repoRoot, bundlePath);

  const install = [
    '#!/usr/bin/env bash',
    'set -eo pipefail',
    '',
    `# asdf repo-toolkit: install the release artifact for a version tag.`,
    `#`,
    `# This script is generated by \`packages/release-artifact/scripts/generate-install.mjs\``,
    `# from the bundled, zero-runtime-dependency installer in`,
    `# \`${bundlePathRel}\`. The embedded bundle applies the exact same`,
    `# archive-header, manifest, required-file, symlink, and wrapper-syntax checks`,
    `# as \`verifyReleaseArtifact\`, so verifier and installer reach equivalent`,
    `# outcomes for any archive.`,
    `#`,
    `# Regenerate after changing the installer:`,
    `#   pnpm --filter @repo-toolkit/release-artifact gen-install`,
    '',
    'tool_name="repo-toolkit"',
    'install_type="$ASDF_INSTALL_TYPE"',
    'version="$ASDF_INSTALL_VERSION"',
    'install_path="$ASDF_INSTALL_PATH"',
    'download_path="$ASDF_DOWNLOAD_PATH"',
    '',
    'if [ "$install_type" != "version" ]; then',
    '  echo "asdf-${tool_name} supports install type \'version\' only (got: ${install_type})" >&2',
    '  exit 1',
    'fi',
    '',
    'if ! command -v node >/dev/null 2>&1; then',
    '  echo "Error: node is required to run ${tool_name}. Install a supported node runtime first." >&2',
    '  exit 1',
    'fi',
    '',
    'shopt -s nullglob',
    'archives=("${download_path}"/*.tar.gz)',
    '',
    'if [ "${#archives[@]}" -ne 1 ]; then',
    '  echo "Expected exactly one release archive in ${download_path}, found ${#archives[@]}." >&2',
    '  exit 1',
    'fi',
    '',
    `echo "Installing \${tool_name} v\${version} from $(basename "\${archives[0]}") ..."`,
    '',
    `node - "\${archives[0]}" "\${install_path}" "\${version}" "\${tool_name}" <<'${MARKER}'`,
    body,
    MARKER,
    '',
    `echo "\${tool_name} v\${version} installed successfully."`,
    '',
  ].join('\n');

  const previous = await readFile(installPath, 'utf8').catch(() => '');
  if (previous === install) {
    process.stdout.write(`${installPathRel} is already up to date.\n`);
    return;
  }

  await writeFile(installPath, install);
  process.stdout.write(`${installPathRel} regenerated from ${bundlePathRel}.\n`);
}

main().catch((error) => {
  console.error(error instanceof Error ? error.message : String(error));
  process.exitCode = 1;
});
